# controller_manager:
#   ros__parameters:
#     update_rate: 30
#     use_sim_time: true

#     diff_cont:
#       type: diff_drive_controller/DiffDriveController

#     joint_broad:
#       type: joint_state_broadcaster/JointStateBroadcaster


# diff_cont:
#   ros__parameters:
#     # type: diff_drive_controller/DiffDriveController
#     publish_rate: 50.0
#     base_frame_id: base_link
#     odom_frame_id: odom
#     left_wheel_names: ["left_wheel_joint"]
#     right_wheel_names: ["right_wheel_joint"]
#     wheel_separation: 0.3
#     wheel_radius: 0.05
#     cmd_vel_timeout: 0.25
#     enable_odom_tf: true
#     publish_cmd: true
#     publish_wheel_data: true



controller_manager:
  ros__parameters:
    update_rate: 100

    # Controllers to load
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_base:
      type: diff_drive_controller/DiffDriveController

# Params for joint state broadcaster
joint_state_broadcaster:
  ros__parameters: {}

# Params for diff drive
diff_drive_base:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link
    odom_frame_id: odom
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.3
    wheel_radius: 0.05
    cmd_vel_timeout: 0.25
    use_stamped_vel: false
    enable_odom_tf: true
    publish_cmd: true
    publish_wheel_data: true
