amcl:
  ros__parameters:
    use_sim_time: True
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "/home/lenny/Documents/GitHub/rdj/baseline_robot_ws/src/robot2025_sim/maps/map.yaml"

planner_server:
  ros__parameters:
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"

behavior_server:
  ros__parameters:
    use_sim_time: True
    bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

global_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 1.0
    static_map: True

local_costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 5.0
    static_map: False

# Robot footprint (adjust to match your robot size)
robot_description:
  ros__parameters:
    footprint: [[0.2,0.15],[0.2,-0.15],[-0.2,-0.15],[-0.2,0.15]]
