slam_toolbox:
  ros__parameters:

    # General
    use_sim_time: true
    mode: mapping  # options: mapping or localization

    # Map
    map_update_interval: 2.0
    resolution: 0.05
    max_laser_range: 10.0

    # Sensor
    scan_topic: /scan
    odom_topic: /diff_drive_base/odom

    # Loop closure
    enable_loop_closure: true
    loop_search_maximum_distance: 3.0
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
